### ISSUE TITLE
Error when running on emulator

### ISSUE THREAD

**Issue by Dersh** [Banuba/face-ar-flutter-sample#11]
Launching lib\main_dev_kuber.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
Debug service listening on ws://127.0.0.1:49501/XsKmxoZbGyY=/ws
Syncing files to device Android SDK built for x86...
E/flutter ( 3657): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method checkPlayServicesAvailability on channel flutter.baseflow.com/google_api_availability/methods)
E/flutter ( 3657): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294:7)
E/flutter ( 3657): <asynchronous suspension>
E/flutter ( 3657): #1      GoogleApiAvailability.checkGooglePlayServicesAvailability (package:google_api_availability/src/google_api_availability.dart:33:26)
E/flutter ( 3657): <asynchronous suspension>
E/flutter ( 3657): #2      isGoogleApiAvailable (package:vmire/code_kit/utils/utils.dart:430:26)
E/flutter ( 3657): <asynchronous suspension>
E/flutter ( 3657): #3      AppManager.initializeComponents (package:vmire/root/models/manager.dart:77:40)
E/flutter ( 3657): <asynchronous suspension>
E/flutter ( 3657): #4      Manager.runMain (package:vmire/root/models/manager.dart:24:5)
E/flutter ( 3657): <asynchronous suspension>
E/flutter ( 3657):

![photo_2022-12-15_17-53-15](https://user-images.githubusercontent.com/28646/208080789-a3ffa5d2-2fea-466b-901b-890203290ca8.jpg)

**Comment by sdk-banuba** [comment]
@Dersh this stacktrace contains no code related to Banuba. It appears to be that this problem should be addressed to Flutter developers.

**Comment by Dersh** [comment]
You are wrong. The reason was that package fails while it's initialisation (`BanubaSdkManager.initialize`) and causes the failure of other package intialization.
We use the following code.
To solve the described issue we have added try-catch. It helped but it is not a target solution.
Are you interested in further investigation?

```
package ar.face.face_ar

import android.content.Context
import android.graphics.Bitmap
import android.util.Log
import android.view.SurfaceView
import android.view.View
import ar.face.face_ar.Messages.FaceArApi
import com.banuba.sdk.camera.Facing
import com.banuba.sdk.effect_player.Effect
import com.banuba.sdk.effect_player.ProcessImageParams
import com.banuba.sdk.entity.ContentRatioParams
import com.banuba.sdk.entity.RecordedVideoInfo
import com.banuba.sdk.manager.BanubaSdkManager
import com.banuba.sdk.manager.IEventCallback
import com.banuba.sdk.types.Data
import io.flutter.embedding.android.FlutterSurfaceView
import io.flutter.embedding.engine.plugins.FlutterPlugin
import io.flutter.plugin.common.StandardMessageCodec
import io.flutter.plugin.platform.PlatformView
import io.flutter.plugin.platform.PlatformViewFactory
import java.io.ByteArrayOutputStream
import java.io.File
import java.util.*
import kotlin.concurrent.thread
import kotlin.math.roundToInt

const val VIEW_TYPE: String = "ar.face.face_ar/view"

/** FaceArPlugin */
class FaceArPlugin : FlutterPlugin, FaceArApi {
    private var banubaSdkManager: BanubaSdkManager? = null
    private var effect: Effect? = null
    private var photoResult: Messages.Result<String>? = null
    private var recordVideoResult: Messages.Result<String>? = null
    private var context: Context? = null
    private var isVideoRecordingInProgress: Boolean = false;

    override fun onAttachedToEngine(flutterPluginBinding: FlutterPlugin.FlutterPluginBinding) {
        try { // added here
            FaceArApi.setup(flutterPluginBinding.binaryMessenger, this)
            BanubaSdkManager.initialize(
                flutterPluginBinding.applicationContext,
                getTokenString(flutterPluginBinding.applicationContext)
            )
            banubaSdkManager = BanubaSdkManager(flutterPluginBinding.applicationContext)
            effect = banubaSdkManager!!.loadEffect(
                BanubaSdkManager.getResourcesBase() + "/effects/Makeup",
                false
            )
            context = flutterPluginBinding.applicationContext
            banubaSdkManager!!.setCallback(object : IEventCallback {
                override fun onCameraOpenError(p0: Throwable) {}

                override fun onCameraStatus(p0: Boolean) {}

                override fun onScreenshotReady(image: Bitmap) {}

                override fun onHQPhotoReady(bitmap: Bitmap) {
                    if (photoResult != null) {
                        val appContext = context
                        if (appContext != null) {
                            thread {
                                try {
                                    val stream = ByteArrayOutputStream()
                                    bitmap.compress(Bitmap.CompressFormat.PNG, 100, stream)
                                    val file =
                                        File("${appContext.cacheDir.path}/${UUID.randomUUID()}.png")
                                    file.writeBytes(stream.toByteArray())
                                    photoResult?.success(file.path)
                                    photoResult = null
                                } catch (e: Throwable) {
                                    photoResult?.error(Exception("Failed to execute image handling. Error: $e"))
                                    photoResult = null
                                }
                            }
                        } else {
                            photoResult?.error(NoContextException())
                            photoResult = null
                        }
                    }
                }

                override fun onVideoRecordingFinished(p0: RecordedVideoInfo) {
                    recordVideoResult?.success(p0.filePath)
                    recordVideoResult = null
                }

                override fun onVideoRecordingStatusChange(p0: Boolean) {}

                override fun onImageProcessed(p0: Bitmap) {}

                override fun onFrameRendered(p0: Data, p1: Int, p2: Int) {}
            })
            flutterPluginBinding.platformViewRegistry
                .registerViewFactory(VIEW_TYPE, FaceArViewFactory(banubaSdkManager!!))
        } catch (e: Throwable) {
            Log.e("FaceAr", "Failed to initialize face_ar plugin", e)
        }
    }


    override fun onDetachedFromEngine(binding: FlutterPlugin.FlutterPluginBinding) {
        try {
            FaceArApi.setup(binding.binaryMessenger, null)
            BanubaSdkManager.deinitialize()
            banubaSdkManager = null
            effect = null
            context = null
            photoResult?.error(Exception("Detached from engine. Photo handling is impossible."))
            photoResult = null
            recordVideoResult?.error(Exception("Detached from engine. Video handling is impossible."))
            recordVideoResult = null
            isVideoRecordingInProgress = false
        } catch (e: Throwable) {
            Log.e("FaceAr", "Failed to deinitialize face_ar plugin", e)
        }
    }

    override fun openCamera() {
        banubaSdkManager!!.effectPlayer.playbackPlay()
        banubaSdkManager!!.openCamera()
    }

    override fun closeCamera() {
        banubaSdkManager!!.effectPlayer.playbackPause()
        banubaSdkManager!!.closeCamera()
    }

    override fun applyColorEffect(colorEffect: Messages.ColorEffect, value: Long) {
        val effectName = when (colorEffect) {
            Messages.ColorEffect.SKIN_COLOR -> "Skin.color"
            Messages.ColorEffect.HAIR_COLOR -> "Hair.color"
            Messages.ColorEffect.EYES_COLOR -> "Eyes.color"
            Messages.ColorEffect.MAKEUP_HIGHLIGHTER -> "Makeup.highlighter"
            Messages.ColorEffect.MAKEUP_CONTOUR -> "Makeup.contour"
            Messages.ColorEffect.MAKEUP_EYELINER -> "Makeup.eyeliner"
            Messages.ColorEffect.MAKEUP_EYESHADOW -> "Makeup.eyeshadow"
            Messages.ColorEffect.LIPS_MATT -> "Lips.matt"
            Messages.ColorEffect.LIPS_SHINY -> "Lips.shiny"
            Messages.ColorEffect.LIPS_GLITTER -> "Lips.glitter"
        }
        effect?.evalJs(makeJsMethod(effectName, getColor(value.toInt())), null)
    }

    override fun applyValueEffect(valueEffect: Messages.ValueEffect, value: Double) {
        val effectName = when (valueEffect) {
            Messages.ValueEffect.EYES_FLARE -> "Eyes.flare"
            Messages.ValueEffect.EYES_WHITENING -> "Eyes.whitening"
            Messages.ValueEffect.FACE_MORPH_EYES -> "FaceMorph.eyes"
            Messages.ValueEffect.FACE_MORPH_FACE -> "FaceMorph.face"
            Messages.ValueEffect.FACE_MORPH_NOSE -> "FaceMorph.nose"
            Messages.ValueEffect.SKIN_SOFTENING -> "Skin.softening"
            Messages.ValueEffect.TEETH_WHITENING -> "Teeth.whitening"
            Messages.ValueEffect.SOFTLIGHT_STRENGTH -> "Softlight.strength"
        }
        effect?.evalJs(makeJsMethod(effectName, value.coerceIn(0.0, 1.0).toString()), null)
    }

    override fun switchCamera() {
        val facing = if (banubaSdkManager!!.cameraFacing == Facing.FRONT) {
            Facing.BACK
        } else {
            Facing.FRONT
        }
        banubaSdkManager!!.setCameraFacing(facing, facing == Facing.FRONT)
    }

    override fun resetValueEffect(valueEffect: Messages.ValueEffect) {
        when (valueEffect) {
            Messages.ValueEffect.EYES_FLARE -> effect?.evalJs(
                makeJsMethod("Eyes.flare", "0.0"),
                null
            )
            Messages.ValueEffect.EYES_WHITENING -> effect?.evalJs(
                makeJsMethod(
                    "Eyes.whitening",
                    "0.0"
                ), null
            )
            Messages.ValueEffect.FACE_MORPH_EYES -> effect?.evalJs(
                makeJsMethod(
                    "FaceMorph.clear",
                    null
                ), null
            )
            Messages.ValueEffect.FACE_MORPH_FACE -> effect?.evalJs(
                makeJsMethod(
                    "FaceMorph.clear",
                    null
                ), null
            )
            Messages.ValueEffect.FACE_MORPH_NOSE -> effect?.evalJs(
                makeJsMethod(
                    "FaceMorph.clear",
                    null
                ), null
            )
            Messages.ValueEffect.SKIN_SOFTENING -> effect?.evalJs(
                makeJsMethod(
                    "Skin.softening",
                    "0.0"
                ), null
            )
            Messages.ValueEffect.TEETH_WHITENING -> effect?.evalJs(
                makeJsMethod(
                    "Teeth.whitening",
                    "0.0"
                ), null
            )
            Messages.ValueEffect.SOFTLIGHT_STRENGTH -> effect?.evalJs(
                makeJsMethod(
                    "Softlight.clear",
                    null
                ), null
            )
        }
    }

    override fun resetColorEffect(colorEffect: Messages.ColorEffect) {
        val resetName = when (colorEffect) {
            Messages.ColorEffect.SKIN_COLOR -> "Skin.clear"
            Messages.ColorEffect.HAIR_COLOR -> "Hair.clear"
            Messages.ColorEffect.EYES_COLOR -> "Eyes.clear"
            Messages.ColorEffect.MAKEUP_HIGHLIGHTER -> "Makeup.clear"
            Messages.ColorEffect.MAKEUP_CONTOUR -> "Makeup.clear"
            Messages.ColorEffect.MAKEUP_EYELINER -> "Makeup.clear"
            Messages.ColorEffect.MAKEUP_EYESHADOW -> "Makeup.clear"
            Messages.ColorEffect.LIPS_MATT -> "Lips.clear"
            Messages.ColorEffect.LIPS_SHINY -> "Lips.clear"
            Messages.ColorEffect.LIPS_GLITTER -> "Lips.clear"
        }
        effect?.evalJs(makeJsMethod(resetName, null), null)
    }

    override fun resetAllEffects() {
        Messages.ColorEffect.values().forEach {
            resetColorEffect(it)
        }
        Messages.ValueEffect.values().forEach {
            resetValueEffect(it)
        }
    }

    override fun takePhoto(result: Messages.Result<String>?) {
        if (photoResult != null) {
            result?.error(Exception("Camera photo is processing"))
        } else {
            banubaSdkManager!!.processCameraPhoto(ProcessImageParams(false, null, null))
            photoResult = result
        }
    }

    override fun stopVideoRecording(result: Messages.Result<String>?) {
        if (recordVideoResult != null) {
            result?.error(Exception("Video has already stopped"))
            return
        }
        if (isVideoRecordingInProgress) {
            recordVideoResult = result
            banubaSdkManager?.stopVideoRecording()
                ?: result?.error(Exception("Sdk Manager is null"))
            isVideoRecordingInProgress = false
        } else {
            result?.error(Exception("Video recording is not started"))
        }
    }

    override fun startVideoRecording(
        isMicrophoneCaptureEnabled: Boolean,
        width: Long,
        height: Long
    ) {
        if (isVideoRecordingInProgress) {
            throw  Exception("Video recording has already started")
        } else {
            val appContext = context
            if (appContext != null) {
                isVideoRecordingInProgress = true
                val path = "${appContext.cacheDir.path}/${UUID.randomUUID()}.mp4"
                banubaSdkManager!!.startVideoRecording(
                    path,
                    isMicrophoneCaptureEnabled,
                    ContentRatioParams(width.toInt(), height.toInt(), false),
                    1F
                )

            } else {
                throw NoContextException()
            }
        }
    }

    private fun getColor(color: Int): String {
        val a: Int = color shr 24 and 0x000000FF
        val r: Int = color shr 16 and 0x000000FF
        val g: Int = color shr 8 and 0x000000FF
        val b: Int = color and 0x000000FF

        val colorArr = listOf(r, g, b, a).map { it.toFloat() / 0xFF }.toFloatArray()
        val colorString = colorArr.joinToString(" ") { v: Float ->
            ((100.0 * v).roundToInt().toFloat() / 100).toString()
        }
        return "'$colorString'"
    }

    private fun makeJsMethod(method: String, params: String?): String {
        return method + if (params == null) "()" else "($params)"
    }

}

private class FaceArViewFactory(
    private val banubaSdkManager: BanubaSdkManager
) : PlatformViewFactory(StandardMessageCodec.INSTANCE) {

    override fun create(
        context: Context,
        id: Int,
        o: Any?
    ): PlatformView = FaceArView(context, banubaSdkManager)
}

class FaceArView internal constructor(
    context: Context,
    private val banubaSdkManager: BanubaSdkManager,
) : PlatformView {

    private val surfaceView: SurfaceView

    init {
        surfaceView = FlutterSurfaceView(context)
        banubaSdkManager.attachSurface(surfaceView)
    }

    override fun getView(): View = surfaceView

    override fun dispose() {
        banubaSdkManager.releaseSurface()
    }
}

fun getTokenString(context: Context): String {
    val stringRes =
        context.resources.getIdentifier("banuba_sdk_token", "string", context.packageName);
    if (stringRes == 0) {
        throw IllegalArgumentException("Не указан токен в поле 'R.string.banuba_sdk_token' файла strings.xml");
    }
    return context.getString(stringRes);
}

class NoContextException : Exception("Context is null")
```
